apiVersion: apps/v1
kind: Deployment
metadata:
  name: math-app-deployment
spec:
  selector:
    matchLabels:
      app: math-app
  replicas: 1
  template:
    metadata:
      labels:
        app: math-app
    spec:
      containers:
      - name: math-container
        image: math-app:latest
        imagePullPolicy: Never
        resources:
          limits:
            cpu: "0.5"
          requests:
            cpu: "0.5"
        ports:
        - containerPort: 5000