apiVersion: apps/v1
kind: Deployment
metadata:
  name: iweb-app-deployment
spec:
  selector:
    matchLabels:
      app: iweb-app
  replicas: 1
  template:
    metadata:
      labels:
        app: iweb-app
    spec:
      containers:
      - name: iweb-container
        image: iweb-app:latest
        imagePullPolicy: Never
        resources:
          limits:
            cpu: "0.5"
          requests:
            cpu: "0.5"
        ports:
        - containerPort: 5000