apiVersion: v1
kind: Service
metadata:
  name: math-app-service
spec:
  type: NodePort
  selector:
    app: math-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30950